# Generated by Django 4.1.2 on 2022-10-23 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=224)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=224)),
                ('telefone1', models.CharField(max_length=12)),
                ('telefone2', models.CharField(max_length=12, null=True)),
                ('logradouro', models.CharField(max_length=224, null=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('complemento', models.CharField(max_length=224, null=True)),
                ('bairo', models.CharField(max_length=224, null=True)),
                ('cidade', models.CharField(max_length=224, null=True)),
                ('estado', models.CharField(max_length=224, null=True)),
                ('pais', models.CharField(max_length=224, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_fantasia', models.CharField(max_length=224)),
                ('razao_social', models.CharField(max_length=224, null=True)),
                ('cnpj', models.CharField(max_length=15)),
                ('ie', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=224)),
                ('telefone1', models.CharField(max_length=12)),
                ('telefone2', models.CharField(max_length=12, null=True)),
                ('logradouro', models.CharField(max_length=224, null=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('bairo', models.CharField(max_length=224, null=True)),
                ('cidade', models.CharField(max_length=224, null=True)),
                ('estado', models.CharField(max_length=224, null=True)),
                ('pais', models.CharField(max_length=224, null=True)),
                ('complemento', models.CharField(max_length=224, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
